---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-kcl-controller
  namespace: "${gitops_namespace}"
spec:
  interval: 5m
  url: https://github.com/kcl-lang/flux-kcl-controller.git
  ignore: |
    /*
    !/config
    /config/*
    !/config/crd
    !/config/manager
  ref:
    tag: v0.1.1
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-kcl-crd
  namespace: "${gitops_namespace}"
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-kcl-controller
  path: ./config/crd
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-kcl-controller
  namespace: "${gitops_namespace}"
spec:
  dependsOn:
    - name: flux-kcl-crd
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-kcl-controller
  path: ./config/manager
  prune: true
  targetNamespace: "${gitops_namespace}"
  patches:
    - patch: |-
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: kcl-controller
        spec:
          template:
            spec:
              serviceAccountName: kustomize-controller
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                      - matchExpressions:
                          - key: kubernetes.io/arch
                            operator: In
                            values:
                              - amd64
    - target:
        kind: Deployment
        name: kcl-controller
      patch: |-
        - op: replace
          path: /spec/template/spec/containers/0/readinessProbe/httpGet/port
          value: http-prom
        - op: replace
          path: /spec/template/spec/containers/0/readinessProbe/httpGet/path
          value: /metrics
        - op: replace
          path: /spec/template/spec/containers/0/livenessProbe/httpGet/port
          value: http-prom
        - op: replace
          path: /spec/template/spec/containers/0/livenessProbe/httpGet/path
          value: /metrics
