---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-app
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kcl-deployment
  namespace: demo-app
spec:
  interval: 30s
  url: https://github.com/awesome-kusion/kcl-deployment.git
  ref:
    branch: main
---
apiVersion: krm.kcl.dev.fluxcd/v1alpha1
kind: KCLRun
metadata:
  name: kcl-deployment
  namespace: demo-app
spec:
  sourceRef:
    kind: GitRepository
    name: kcl-deployment
